"""
EduHub SaaS UI Blueprint & Theme Engine
Theme: Linear Pro Max Dark Aesthetic (2026)
Standards: Linear, Stripe, Raycast dark neon & frosted glass design system.
"""
import os
import json

class EduHubThemeEngine:
    def __init__(self):
        self.theme_name = "Linear Pro Max Dark Aesthetic (2026)"
        self.ui_blueprint = {
            "GLOBAL_STYLES": {
                "background_color": "#030712",
                "text_primary": "#FFFFFF",
                "text_muted": "#94A3B8",
                "font_headings": "Montserrat, system-ui, sans-serif",
                "font_body": "Inter, system-ui, sans-serif"
            },
            "PREMIUM_COMPONENTS": {
                "card_style": {
                    "background": "rgba(17, 24, 39, 0.7)",
                    "border_radius": "16px",
                    "border": "1px solid rgba(255, 255, 255, 0.08)",
                    "backdrop_filter": "blur(12px)",
                    "hover_effect": "border-color: #4F46E5; box-shadow: 0 0 25px rgba(79, 70, 229, 0.15);"
                },
                "glow_button_cta": {
                    "background": "linear-gradient(135deg, #2563EB 0%, #4F46E5 50%, #7C3AED 100%)",
                    "border_radius": "12px",
                    "font_weight": "700",
                    "transition": "all 0.2s ease-in-out",
                    "transform_on_hover": "scale(1.02)",
                    "glow_on_hover": "0 0 20px rgba(99, 102, 241, 0.4)"
                },
                "sandbox_chat_input": {
                    "background": "#0B0F19",
                    "border_active": "1px solid #3B82F6",
                    "shadow_active": "0 0 15px rgba(59, 130, 246, 0.2)",
                    "placeholder_color": "#475569"
                }
            },
            "UX_LOGIC": {
                "tabs_navigation": "Enabled (Smooth crossfade between Hub, Resume, and Factories)",
                "paywall_blur_effect": "Active (Blur last 70% of AI response text for non-paying users)",
                "loading_animation": "Ultra-low-latency typing effect (Gemini 2.5 Flash stream optimization)"
            }
        }

    def export_css_variables(self, filename="static/css/premium_theme.css"):
        """Генерирует расширенный CSS-код премиальной дизайн-системы для деплоя на Render."""
        os.makedirs(os.path.dirname(filename), exist_ok=True)
        css_content = f"""/* 
   ==========================================================================
   💎 EDUHUB AI PREMIUM DESIGN SYSTEM CONFIGURATION
   Theme: {self.theme_name}
   Generated by: Autonomous SaaS CEO Agent
   Standards: Linear, Stripe & Raycast Dark Aesthetics (2026)
   ========================================================================== */

@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Montserrat:wght@600;700;800;900&display=swap');

:root {{
    --bg-global: {self.ui_blueprint['GLOBAL_STYLES']['background_color']};
    --text-main: {self.ui_blueprint['GLOBAL_STYLES']['text_primary']};
    --text-muted: {self.ui_blueprint['GLOBAL_STYLES']['text_muted']};
    --font-head: {self.ui_blueprint['GLOBAL_STYLES']['font_headings']};
    --font-body: {self.ui_blueprint['GLOBAL_STYLES']['font_body']};
    --linear-glass: rgba(17, 24, 39, 0.7);
    --linear-border: rgba(255, 255, 255, 0.08);
    --linear-accent-blue: #2563EB;
    --linear-accent-indigo: #4F46E5;
    --linear-accent-purple: #7C3AED;
}}

body {{
    font-family: var(--font-body);
    background-color: var(--bg-global);
    color: var(--text-main);
}}

h1, h2, h3, h4, .font-heading {{
    font-family: var(--font-head);
}}

/* ==========================================================================
   PREMIUM GLASS & CARD COMPONENTS
   ========================================================================== */
.premium-card {{
    background: {self.ui_blueprint['PREMIUM_COMPONENTS']['card_style']['background']};
    border-radius: {self.ui_blueprint['PREMIUM_COMPONENTS']['card_style']['border_radius']};
    border: {self.ui_blueprint['PREMIUM_COMPONENTS']['card_style']['border']};
    backdrop-filter: {self.ui_blueprint['PREMIUM_COMPONENTS']['card_style']['backdrop_filter']};
    -webkit-backdrop-filter: {self.ui_blueprint['PREMIUM_COMPONENTS']['card_style']['backdrop_filter']};
    transition: all 0.3s cubic-bezier(0.16, 1, 0.3, 1);
}}

.premium-card:hover {{
    border-color: #4F46E5;
    box-shadow: 0 0 25px rgba(79, 70, 229, 0.2), 0 10px 30px -10px rgba(0, 0, 0, 0.5);
    transform: translateY(-2px);
}}

/* ==========================================================================
   GLOW BUTTON CTA (LINEAR / STRIPE STYLE)
   ========================================================================== */
.glow-btn-cta {{
    background: {self.ui_blueprint['PREMIUM_COMPONENTS']['glow_button_cta']['background']};
    border-radius: {self.ui_blueprint['PREMIUM_COMPONENTS']['glow_button_cta']['border_radius']};
    font-weight: {self.ui_blueprint['PREMIUM_COMPONENTS']['glow_button_cta']['font_weight']};
    transition: {self.ui_blueprint['PREMIUM_COMPONENTS']['glow_button_cta']['transition']};
    position: relative;
    overflow: hidden;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    text-shadow: 0 1px 2px rgba(0, 0, 0, 0.3);
}}

.glow-btn-cta:hover {{
    transform: {self.ui_blueprint['PREMIUM_COMPONENTS']['glow_button_cta']['transform_on_hover']};
    box-shadow: {self.ui_blueprint['PREMIUM_COMPONENTS']['glow_button_cta']['glow_on_hover']};
}}

.glow-btn-cta:active {{
    transform: scale(0.98);
}}

/* ==========================================================================
   SANDBOX CHAT INPUT (ULTRA-DARK ELEVATED)
   ========================================================================== */
.sandbox-chat-input {{
    background-color: {self.ui_blueprint['PREMIUM_COMPONENTS']['sandbox_chat_input']['background']} !important;
    border: 1px solid rgba(255, 255, 255, 0.1) !important;
    color: #F8FAFC !important;
    transition: all 0.25s ease !important;
}}

.sandbox-chat-input:focus {{
    border: {self.ui_blueprint['PREMIUM_COMPONENTS']['sandbox_chat_input']['border_active']} !important;
    box-shadow: {self.ui_blueprint['PREMIUM_COMPONENTS']['sandbox_chat_input']['shadow_active']} !important;
    outline: none !important;
}}

.sandbox-chat-input::placeholder {{
    color: {self.ui_blueprint['PREMIUM_COMPONENTS']['sandbox_chat_input']['placeholder_color']};
}}

/* ==========================================================================
   INTERACTIVE SEGMENTED TABS CONTROLLER (LINEAR / RAYCAST STYLE)
   ========================================================================== */
.segmented-tabs-container {{
    display: flex;
    background: rgba(11, 15, 25, 0.85);
    border: 1px solid rgba(255, 255, 255, 0.08);
    border-radius: 18px;
    padding: 6px;
    gap: 6px;
    backdrop-filter: blur(16px);
    box-shadow: 0 10px 30px -10px rgba(0, 0, 0, 0.6), inset 0 1px 1px rgba(255, 255, 255, 0.05);
}}

.segmented-tab-btn {{
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 8px;
    padding: 12px 20px;
    font-family: var(--font-head);
    font-size: 13px;
    font-weight: 700;
    color: #94A3B8;
    background: transparent;
    border-radius: 12px;
    border: 1px solid transparent;
    transition: all 0.25s cubic-bezier(0.16, 1, 0.3, 1);
    cursor: pointer;
    user-select: none;
}}

.segmented-tab-btn:hover {{
    color: #FFFFFF;
    background: rgba(255, 255, 255, 0.04);
}}

.segmented-tab-btn.active-tab-hub {{
    color: #FFFFFF;
    background: linear-gradient(135deg, #1D4ED8 0%, #2563EB 100%);
    box-shadow: 0 0 20px rgba(37, 99, 235, 0.35);
    border-color: rgba(96, 165, 250, 0.4);
}}

.segmented-tab-btn.active-tab-resume {{
    color: #FFFFFF;
    background: linear-gradient(135deg, #047857 0%, #059669 100%);
    box-shadow: 0 0 20px rgba(16, 185, 129, 0.35);
    border-color: rgba(52, 211, 153, 0.4);
}}

.segmented-tab-btn.active-tab-factories {{
    color: #FFFFFF;
    background: linear-gradient(135deg, #6D28D9 0%, #7C3AED 100%);
    box-shadow: 0 0 20px rgba(124, 58, 237, 0.35);
    border-color: rgba(192, 132, 252, 0.4);
}}

/* Crossfade transitions for Tab Panes */
.tab-pane-crossfade {{
    opacity: 0;
    transform: translateY(8px);
    transition: opacity 0.35s ease, transform 0.35s cubic-bezier(0.16, 1, 0.3, 1);
    display: none;
}}

.tab-pane-crossfade.pane-visible {{
    display: block;
    opacity: 1;
    transform: translateY(0);
}}

/* ==========================================================================
   PAYWALL BLUR EFFECT & GRADIENT MASK (LAST 70% OF RESPONSE)
   ========================================================================== */
.paywall-container {{
    position: relative;
    overflow: hidden;
}}

.paywall-blur-mask {{
    filter: blur(5px);
    user-select: none;
    pointer-events: none;
    mask-image: linear-gradient(to bottom, rgba(0, 0, 0, 1) 0%, rgba(0, 0, 0, 0.4) 40%, rgba(0, 0, 0, 0) 90%);
    -webkit-mask-image: linear-gradient(to bottom, rgba(0, 0, 0, 1) 0%, rgba(0, 0, 0, 0.4) 40%, rgba(0, 0, 0, 0) 90%);
    opacity: 0.55;
    max-height: 240px;
    overflow: hidden;
}}

.paywall-floating-overlay {{
    position: absolute;
    inset: 0;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: flex-end;
    padding-bottom: 24px;
    background: linear-gradient(to bottom, rgba(3, 7, 18, 0) 0%, rgba(3, 7, 18, 0.85) 60%, rgba(3, 7, 18, 0.98) 100%);
    z-index: 20;
}}

.paywall-glass-card {{
    background: rgba(15, 23, 42, 0.88);
    border: 1px solid rgba(124, 58, 237, 0.45);
    box-shadow: 0 0 35px rgba(124, 58, 237, 0.3), 0 20px 40px -15px rgba(0, 0, 0, 0.85);
    backdrop-filter: blur(18px);
    -webkit-backdrop-filter: blur(18px);
    border-radius: 20px;
    padding: 22px 26px;
    text-align: center;
    max-width: 520px;
    width: 92%;
    animation: paywallPulseGlow 3s infinite alternate ease-in-out;
}}

@keyframes paywallPulseGlow {{
    0% {{
        box-shadow: 0 0 20px rgba(124, 58, 237, 0.2), 0 10px 25px rgba(0, 0, 0, 0.7);
    }}
    100% {{
        box-shadow: 0 0 38px rgba(124, 58, 237, 0.45), 0 15px 35px rgba(0, 0, 0, 0.9);
    }}
}}
"""
        with open(filename, "w", encoding="utf-8") as f:
            f.write(css_content)
        return f"[SUCCESS] Премиальная дизайн-система скомпилирована в: {filename}"

if __name__ == "__main__":
    engine = EduHubThemeEngine()
    print(engine.export_css_variables())
